/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "media",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontSize: {
        "heading-xs": [
          "clamp(1.25rem, 2.5vw, 2rem)",
          { lineHeight: "1.1", letterSpacing: "-0.02em" },
        ],
        "heading-sm": [
          "clamp(1.5rem, 3.5vw, 2.5rem)",
          { lineHeight: "1.1", letterSpacing: "-0.03em" },
        ],
        "heading-md": [
          "clamp(1.875rem, 4.5vw, 3.5rem)",
          { lineHeight: "1.05", letterSpacing: "-0.03em" },
        ],
        "heading-lg": [
          "clamp(2.5rem, 6vw, 5rem)",
          { lineHeight: "1", letterSpacing: "-0.04em" },
        ],
        "heading-xl": [
          "clamp(3rem, 8vw, 6.5rem)",
          { lineHeight: "0.95", letterSpacing: "-0.04em" },
        ],
        "heading-xxl": [
          "clamp(3.5rem, 10vw, 9rem)",
          { lineHeight: "0.9", letterSpacing: "-0.05em" },
        ],
      },
      spacing: {
        xs: "0.5rem" /* 8px */,
        sm: "1rem" /* 16px */,
        md: "1.5rem" /* 24px */,
        lg: "2rem" /* 32px */,
        xl: "3rem" /* 48px */,
        "2xl": "4rem" /* 64px */,
        "3xl": "6rem" /* 96px */,
        "4xl": "8rem" /* 128px */,
        "5xl": "10rem" /* 160px */,
        "6xl": "12rem" /* 192px */,
      },
      colors: {
        border: "var(--border)",
        accent: "var(--surface-bright)",
        "text-primary": "var(--on-surface)",
        "text-secondary": "var(--on-surface-variant)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-secondary-fixed-variant": "#9e005e",
        "on-secondary-fixed": "#6b003e",
        "on-tertiary-fixed": "#2e0e00",
        "secondary-fixed-dim": "#ffaccb",
        "error-container": "#7f2927",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-bright": "var(--surface-bright)",
        "secondary-fixed": "#ffc1d6",
        error: "#ee7d77",
        "on-secondary": "#202022",
        "surface-container-high": "var(--surface-container-high)",
        "tertiary-fixed-dim": "#e6c047",
        "on-secondary-container": "#c1bec1",
        "secondary-dim": "#9f9da0",
        "on-primary-fixed": "#003d83",
        surface: "var(--surface)",
        "tertiary-fixed": "#f5ce53",
        "on-error": "#490106",
        background: "var(--background)",
        "on-error-container": "#ff9993",
        "primary-fixed-dim": "#c2d4ff",
        "on-primary-container": "#bcd0ff",
        primary: "#acc7ff",
        "outline-variant": "var(--outline-variant)",
        outline: "var(--outline)",
        "error-dim": "#bb5551",
        "on-surface": "var(--on-surface)",
        "on-tertiary-container": "#584500",
        "inverse-primary": "#245db1",
        "on-primary": "#003e85",
        "primary-container": "#004492",
        "primary-fixed": "#d7e2ff",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "secondary-container": "#3b3b3d",
        secondary: "#9f9da0",
        "on-tertiary": "#624e00",
        "on-background": "var(--on-surface)",
        "surface-dim": "var(--surface-dim)",
        "inverse-surface": "var(--inverse-surface)",
        "primary-dim": "#96b9ff",
        "on-primary-fixed-variant": "#1e59ae",
        "surface-variant": "var(--surface-variant)",
        "on-tertiary-fixed-variant": "#634e00",
        "tertiary-container": "#f5ce53",
        "surface-container-low": "var(--surface-container-low)",
        tertiary: "#ffdd79",
        "surface-container": "var(--surface-container)",
      },
      fontFamily: {
        heading: ["Manrope", "sans-serif"],
        display: ["Manrope", "sans-serif"],
        serif: ["Instrument Serif", "serif"],
        mono: ["Courier New", "monospace"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
